### ISSUE TITLE
Converting pages where name includes parentheses

### ISSUE THREAD

**Issue by frauzufall** [imagej/imagej.github.io#16]
Currently the conversion fails with pages like `ImgLib1_(deprecated).mw`:
```
running pandoc on file: ImgLib1_(deprecated).mw
sh: 1: Syntax error: "(" unexpected
Traceback (most recent call last):
  File "mass_convert.py", line 56, in <module>
    iteratively_convert(root_in, root_out, page_title)
  File "mass_convert.py", line 27, in iteratively_convert
    convertLinks(path_out, root_in, root_out)
  File "mass_convert.py", line 48, in convertLinks
    iteratively_convert(root_in, root_out, link)
  File "mass_convert.py", line 27, in iteratively_convert
    convertLinks(path_out, root_in, root_out)
  File "mass_convert.py", line 48, in convertLinks
    iteratively_convert(root_in, root_out, link)
  File "mass_convert.py", line 27, in iteratively_convert
    convertLinks(path_out, root_in, root_out)
  File "mass_convert.py", line 48, in convertLinks
    iteratively_convert(root_in, root_out, link)
  File "mass_convert.py", line 26, in iteratively_convert
    convertFile(path_in, path_out)
  File "mass_convert.py", line 31, in convertFile
    run_pandoc(path_in, path_out)
  File "/media/data/Development/imagej/imagej/imagej.github.io/convert/ij_mw_preprocess.py", line 143, in run_pandoc
    content_tmp = read_file(path_out)
  File "/media/data/Development/imagej/imagej/imagej.github.io/convert/ij_mw_preprocess.py", line 8, in read_file
    with open(file_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/random/Development/imagej/imagej/imagej.github.io/pages/ImgLib1_(deprecated).md'

```
Does pandoc not process these file names?

**Comment by frauzufall** [comment]
All parentheses are now removed from page names 4faae398ec8782eb9003bc2b6747ddfd50f3ff3b
